FROM php:8.0-apache

RUN a2enmod rewrite
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apt-get update && apt-get install -y zip unzip vim
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html/

COPY src/ /var/www/html

WORKDIR /var/www/html/L9x/

RUN composer update

WORKDIR /var/www/html/L8x/

RUN composer update

WORKDIR /var/www/html/

RUN chmod 777 -R L9x/storage
RUN chmod 777 -R L8x/storage


COPY config/php8.ini /usr/local/etc/php/

EXPOSE 80/tcp
